version: '3.8'

services:
  email-analysis-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-phishing-analyzer
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - email-analysis-network

  # Optional: Add Redis for caching results (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: email-analysis-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - email-analysis-network

  # Optional: Add PostgreSQL for storing analysis results (uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: email-analysis-db
  #   environment:
  #     POSTGRES_DB: email_analysis
  #     POSTGRES_USER: analyzer
  #     POSTGRES_PASSWORD: secure_password_123
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - email-analysis-network

networks:
  email-analysis-network:
    driver: bridge

# Uncomment if using optional services
# volumes:
#   redis_data:
#   postgres_data:
